common:
    lid_topic:  "/ns1/velodyne_points"
    imu_topic:  "/imu/data_raw"
    time_sync_en: true         # ONLY turn on when external time synchronization is really not possible
    
preprocess:
    lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 16
    blind: 1

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    360
    det_range:     100.0
    extrinsic_T: [ -0.366669, -0.411346, 0.24785]
    extrinsic_R: [ -0.512596, 0.700555, -0.496456,
                   -0.497638, -0.713576, -0.493119,
                   -0.699716, -0.00571531, 0.714398]

publish:     
    scan_publish_en:  true       # 'false' will close all the point cloud output
    dense_publish_en: true       # false will low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # output the point cloud scans in IMU-body-frame